apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: $PREFIX
spec:
  groups:
  - system:authenticated
  request: $ENCODED_CSR
  usages:
  - digital signature
  - key encipherment
  - client auth
